### ISSUE TITLE
.log files management

### ISSUE THREAD

**Issue by SebastienPeillet** [olivierhagolle/maja_peps#1]
Hi @olivierhagolle ,

I'm testing this new tool and I notice that for the maja_peps_process.py script, the .log files are created in the current working directory and maja_peps_download.py searchs them also in the cwd. It forces users to launch both script from the same cwd, otherwise maja_peps_download.py doesn't find .log files.

In my experience I get an issue because I use another script to launch maja_peps_process.py with a shapefile as location input. I use this script from a folder "A". Then I wait that the products are ready and I simply launch maja_peps_download.py with the maja_peps folder as cwd, but obviously it doesn't find the log files that has been created  in "A" and not in maja_peps folder.

As it take one or two hours to treat data and that the user will probably change directory during this time, would it be not easier to force the output directory for .log files to avoid this ? For my part I fix the issue by using the same directory for the prod_list output and the log files (and looking for them in the same directory in maja_peps_download.py) as prod_list output is a required argument for both process and download script. But it's also possible to do it with the maja_peps folder !

I can provide the bug fix for the first solution if you want.

Thank for this tools !

**Comment by olivierhagolle** [comment]
Merci Sebastien,
I know it is not very convenient, but I lack time these days.
The simplest would be to store the temp files in the directory passed with -w argument, or in CWD is argument is not provided.

If you want to do it, it would be nice !
Olivier
