### ISSUE TITLE
Encoding issue when request is written into the log file

### ISSUE THREAD

**Issue by Seam8** [olivierhagolle/maja_peps#11]
`$ python3 ./full_maja_process.py -t 31TCJ -a peps.txt -d 2017-07-01 -f 2018-01-01 -g 31TCJ_20170101.log
http://peps.cnes.fr/resto/wps?request=execute&service=WPS&version=1.0.0&identifier=FULL_MAJA&datainputs=startDate=2017-07-01;completionDate=2018-01-01;tileid=31TCJ&status=true&storeExecuteResponse=true
Traceback (most recent call last):
  File "./full_maja_process.py", line 208, in <module>
    f.write(req.text.encode('utf-8'))
TypeError: write() argument must be str, not bytes`

It look like the request contains special characters which may not be supported by the format.

**Comment by Seam8** [comment]
The error is triggered in Python 3 only.

**Comment by olivierhagolle** [comment]
Thanks for the bug report.
There seems to be an issue with python 3, we will try to correct it.
Meanwhile, It works with python 2.7

by the way, we changed a little bit the command line in this morning's update (-f => -e, -f => -l)
 python ./full_maja_process.py -t 31TFJ -a peps.txt -d 2017-07-01 -e 2018-01-01 -l 31TFJ_20170101.log

**Comment by olivierhagolle** [comment]
You won by 1 minute...

**Comment by olivierhagolle** [comment]
Hi again, 
I think it now works for both versions
Olivier

**Comment by Seam8** [comment]
I notice the efficiency.
Indeed, it runs perfectly now with python 3 and command line is now more logic to me. 
Thank you !

**Comment by Seam8** [comment]
`Traceback (most recent call last):
  File "full_maja_download.py", line 147, in <module>
    lignes = f.readlines()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1074: ordinal not in range(128)
`

Yet, full_maja_download.py is also running into the same kind of issue. 
It is not a big deal for me, as I can request download with python2 but I just report the bug. 
Best

**Comment by olivierhagolle** [comment]
Thanks, I can't reproduce it until the process I launched comes to an end. Still 5% to go...

**Comment by olivierhagolle** [comment]
It seems to be working now with both python2 and python 3 (tested 3.5.2), but I had to use a 
`if sys.version_info[0] < 3:`
