### ISSUE TITLE
Wrong request status 500

### ISSUE THREAD

**Issue by c00kiemon5ter** [olivierhagolle/maja_peps#13]
Hello, and thanks for making all those tools.

I'm trying to use maja_peps to request processing of a tile, but I get an error. Is this service still running and available? Am I doing something wrong?

```bash
$ python ./full_maja_process.py -t 34SEG -a peps.ivan.txt -d 2019-04-01 -e 2019-08-31 -l 34SEG_2019.log
http://peps.cnes.fr/resto/wps?request=execute&service=WPS&version=1.0.0&identifier=FULL_MAJA&datainputs=startDate=2019-04-01;completionDate=2019-08-31;tileid=34SEG&status=true&storeExecuteResponse=true
---------------------------------------------------------------------------
Wrong request status 500
---------------------------------------------------------------------------
```

**Comment by olivierhagolle** [comment]
Hi, I have asked @christophetaillan who developed this service. There was a system upgrade on CNES HPC yesterday, maybe is it a collateral effect.

**Comment by olivierhagolle** [comment]
Christophe says the service has been restarted ( I did not test it yet)

**Comment by c00kiemon5ter** [comment]
Seems to be working! I successfully submitted a job. Thank you!

**Comment by c00kiemon5ter** [comment]
@olivierhagolle can we get some more details on the MAJA setup on PEPS?

- which version of MAJA are you using?
- do you use srtm or eu-dem?
- do you include CAMS?

thanks again!

**Comment by olivierhagolle** [comment]
Good questions. It's MAJA 3.2 so far, with SRTM and without CAMS
Olivier
