### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by intiluna** [olivierhagolle/maja_peps#7]
The following run of peps_maja_process.py on a Ubuntu 18.04.2 LTS /64 bit/GNOME 3.28.2 system using curl 7.58.0:
python /home/intiluna/peps/peps_maja/maja_peps-master/peps_maja_process.py 2 --lonmin -87.38307 --lonmax -86.68346 --latmin 12.19383 --latmax 12.88708 -a /home/intiluna/peps/peps_maja/maja_peps-master/peps.txt -d 2018-11-31 -f 2018-12-31 -p prod_list_gob2018-11-31_2018_12_31.txt
Produces the following error:
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?box=-87.38307,12.19383,-86.68346,12.88708\&startDate=2018-11-31\&completionDate=2018-12-31\&maxRecords=500\&productType=S2MSI1C
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    60  100    60    0     0    110      0 --:--:-- --:--:-- --:--:--   110
Database connection error

The search.json file is created with only one line with the following message:
{"ErrorMessage":"Database connection error","ErrorCode":500}

##curl info:
intiluna@baba20:~/peps/descarga/Nicaragua201812$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

I went to peps website and tested my user and pw, all working fine and I was able to process and download images interactively.

What could be the problem?
Thanks a lot,

**Comment by olivierhagolle** [comment]
Thanks for the bug report, and sorry for that. 
I have been able to reproduce the error. I will ask the peps people what is wrong. Some security patches have been applied recently, I guess it is now too secure ;)
Olivier

**Comment by olivierhagolle** [comment]
Ok, the error is due to " -d 2018-11-31", as there is no 31st of November (but the peps message could be more explicit). Could you try with December 1st instead ?
Best regards,
Olivier

**Comment by intiluna** [comment]
Hello Olivier,
I confirm the issue is solved. The problem is about the dates as you mentioned and indeed the "Database connection error" is quite vague.  Thanks a lot!
