### ISSUE TITLE
re-download

### ISSUE THREAD

**Issue by aloboa** [olivierhagolle/maja_peps#8]
Some (few) zip files are corrupte. perhaps because of transfer issues.
In those cases, is it possible to download again those faulty zip files only?
I've tried to locate the faultu zip file in the prod_list file, but naming are not the same...

**Comment by olivierhagolle** [comment]
Oops, It seems I missed this message. Sorry Agustin !
As a new version is available, I am closing the issue, feel free to reopen it if necessary

**Comment by aloboa** [comment]
Despite the new version, having some corrupted zip files because of transfer problems is still a possibility. Is there a way of transfering again some zip files?

**Comment by olivierhagolle** [comment]
Launching the command again should download the removed files again 
Olivier
